name: WTask
main: cc.crazywhale.WTask.WTask
api: [1.0.0]
version: "1.1.0"
author: Whale

load: POSTWORLD
description: WTask nukkit版本build1

permissions:
  wtask.command.op:
    default: op
  wtask.command.player:
    default: true
  wtask.command.wt:
    default: true
  wtask.command.wtask:
    default: op
  op:
    default: op
  "true":
    default: true