name: WTask
main: cc.crazywhale.WTask.WTask
api: [1.0.0]
version: "1.0.1"
author: Whale

load: POSTWORLD
description: WTask nukkit版本build1

permissions:
  wtask.command.op:
    default: op
  wtask.command.player:
    default: true